version: '3.3'
services:
  hapi-fhir-openemr:
#    image: thedemoland/hapi-fhir-postgres
#    image: loner7/hapi-fhir-open-emr:master8dc40f9475b892f713743d655a08b1da36c4c9b9
    image: loner7/hapi-fhir-open-emr:master1de10633d4e329cd8c356a3d8ab892ffbefe1f65
    container_name: fhir-openemr
    ports:
    - '8081:8080'
    restart: always
  hapi-fhir-postgres:
#    image: thedemoland/hapi-fhir-postgres
#    image: loner7/hapi-fhir-postgres:master8dc40f9475b892f713743d655a08b1da36c4c9b9
    image: loner7/hapi-fhir-postgres:master1de10633d4e329cd8c356a3d8ab892ffbefe1f65
    container_name: fhir-postgres
    ports:
      - '8080:8080'
    restart: always
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: hapi-persist-db
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '80:80'
    links:
      - "db:pgsql-server"
    restart: unless-stopped
volumes:
  pgdata:
  pgadmin:
