
name: HAPI FHIR Build

on:
  push:
    branches: [ master , dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Get code
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          
      - name: Step 3 - Build project
        run: mvn compile jib:build
