
name: HAPI FHIR Build

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Step 1 - Get code
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: '11'
          
      # - name: Step 3 - Login to Docker Hub
      #   uses: docker/login-action@v1.9.0
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Step 3 - Start container
      #   id: docker-compose
      #   run: docker-compose up -d 

      - name: Step 4 - Generate coverage
        id: coverage-generate
        run: mvn -B verify --no-transfer-progress

      - run: mvn jacoco:report 

      - run: ls

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
      
      - name: Step 5 - Test slack
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#general'
        if: always()
    

      
